
import java.awt.Color;
import java.awt.Font;
import static java.awt.Font.ITALIC;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 123
 */
public class Hospital extends javax.swing.JFrame {

DefaultTableModel model;
    public Hospital() {
        initComponents();

        this.fillHospitalJtable(jTable1, "");
    model =(DefaultTableModel)jTable1.getModel();
    jTable1.setRowHeight(40);
    jTable1.setShowGrid(true);
    jTable1.setGridColor(Color.yellow);
    jTable1.setSelectionBackground(Color.BLACK);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_refer = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_number = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_dosemg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_LOT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Issued = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Exp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField_Dose = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Effects = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField_machine = new javax.swing.JTextField();
        jTextField_further = new javax.swing.JTextField();
        jTextField_advice = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        jTextField_medication = new javax.swing.JTextField();
        jTextField_pid = new javax.swing.JTextField();
        jTextField_nhs = new javax.swing.JTextField();
        jTextField_birth = new javax.swing.JTextField();
        jTextField_address = new javax.swing.JTextField();
        jComboBox_tablets = new javax.swing.JComboBox<>();
        text_area = new java.awt.TextArea();
        jButton_Delete = new javax.swing.JButton();
        jButton_add = new javax.swing.JButton();
        jButton_patient = new javax.swing.JButton();
        jButton_Reset = new javax.swing.JButton();
        jButton_Prescription = new javax.swing.JButton();
        jButton_print = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_Update = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();

        jTextField_refer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_referActionPerformed(evt);
            }
        });
        jTextField_refer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_referKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_referKeyTyped(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 255, 51));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("  Hospital Management System");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Patient Prescription");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name of Tablets:-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Reference No:-");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Dose(mg):-");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Number of tablets:-");

        jTextField_dosemg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_dosemgActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("LOT:-");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Exp Date:-");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Issued Date:-");

        jTextField_Exp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_ExpKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Daily Dose:-");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Possible Side Effects:-");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Patient ID");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Further information:-");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Storage Advice:-");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Driving and Using Machines:-");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("How to Use Medication:-");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Patient Address");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("NHS Number");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Patient Name");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Date of Birth");

        jTextField_machine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_machineActionPerformed(evt);
            }
        });

        jTextField_further.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_furtherActionPerformed(evt);
            }
        });

        jTextField_advice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_adviceActionPerformed(evt);
            }
        });

        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });

        jTextField_medication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_medicationActionPerformed(evt);
            }
        });

        jTextField_pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_pidActionPerformed(evt);
            }
        });
        jTextField_pid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_pidKeyTyped(evt);
            }
        });

        jTextField_nhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nhsActionPerformed(evt);
            }
        });
        jTextField_nhs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nhsKeyTyped(evt);
            }
        });

        jTextField_birth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_birthActionPerformed(evt);
            }
        });
        jTextField_birth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_birthKeyTyped(evt);
            }
        });

        jTextField_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addressActionPerformed(evt);
            }
        });

        jComboBox_tablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Make a selection", "flexon", "combiflan", "Elavil", "Exforge", "Norvasc", "Exforge HCT" }));
        jComboBox_tablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tabletsActionPerformed(evt);
            }
        });

        text_area.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        text_area.setForeground(new java.awt.Color(255, 255, 102));

        jButton_Delete.setBackground(new java.awt.Color(255, 255, 51));
        jButton_Delete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Delete.setText("Delete");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        jButton_add.setBackground(new java.awt.Color(255, 255, 51));
        jButton_add.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_patient.setBackground(new java.awt.Color(255, 255, 51));
        jButton_patient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_patient.setText("Patient");
        jButton_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_patientActionPerformed(evt);
            }
        });

        jButton_Reset.setBackground(new java.awt.Color(255, 255, 51));
        jButton_Reset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Reset.setText("Reset");
        jButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetActionPerformed(evt);
            }
        });

        jButton_Prescription.setBackground(new java.awt.Color(255, 255, 51));
        jButton_Prescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Prescription.setText("Prescription");
        jButton_Prescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_PrescriptionActionPerformed(evt);
            }
        });

        jButton_print.setBackground(new java.awt.Color(255, 255, 51));
        jButton_print.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_print.setText("Print");
        jButton_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_printActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 255, 51));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setText("Exit");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name of Tablets", "Reference No", "Dose(mg)", "Number of tablets", "LOT", "Issued Date", "Exp Date", "Daily Dose", "Possible Side Effect ", "Further information", "Storage Advice", "Driving and using Machin", "How to use Medication", "Patient ID", "NHS Number", "Patient Name", "Date of Birth", "Patient Address"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jButton_Update.setBackground(new java.awt.Color(255, 255, 51));
        jButton_Update.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Update.setText("Edit");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Id:-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Prescription)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Update)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(87, 87, 87)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel10)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(109, 109, 109)
                                                .addComponent(jLabel23))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(69, 69, 69)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel6))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(136, 136, 136)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_dosemg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_number, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_Issued, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_Exp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_LOT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox_tablets, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_Effects, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_Dose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(52, 52, 52)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_nhs, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_pid, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_medication, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_machine)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_further, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                    .addComponent(jTextField_advice))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_area, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(1402, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jButton_print, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1407, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_further, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel14)
                                            .addComponent(jTextField_advice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jComboBox_tablets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(253, 253, 253)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(text_area, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(jTextField_dosemg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_nhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_LOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jTextField_Issued, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(24, 24, 24)
                        .addComponent(jTextField_Dose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Effects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel11)
                            .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField_machine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_medication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_birth, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_print, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Prescription, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_machineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_machineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_machineActionPerformed

    private void jTextField_adviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_adviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_adviceActionPerformed

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void jTextField_medicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_medicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_medicationActionPerformed

    private void jTextField_pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_pidActionPerformed
        
    }//GEN-LAST:event_jTextField_pidActionPerformed

    private void jTextField_nhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nhsActionPerformed

    private void jTextField_birthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_birthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_birthActionPerformed

    private void jTextField_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addressActionPerformed

    private void jComboBox_tabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tabletsActionPerformed
           
    }//GEN-LAST:event_jComboBox_tabletsActionPerformed

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        if(jTextField_Dose.getText().equals("")){
        JOptionPane.showMessageDialog(null, "please enter your dose");
        
        }
        else{
        Connection con=MyConnection.getConnection();
        PreparedStatement ps;
        try {
            ps=con.prepareStatement("INSERT INTO `patient`(`Name_of_Tablets`, `Reference_No`, `Dose_mg`, `Number_of_Tablets`, `LOT`, `Issued_Date`, `Exp_Date`, `Daily_Dose`, `Possible_Side_Effects`, `Further_information`, `Storage_Advice`, `Driving_and_Using_Machines`, `How_to_Use_Medication`, `Patient_ID`, `NHS_number`, `Patient_Name`, `Date_of_Birth`, `Patient_Address`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            String value=(String) jComboBox_tablets.getSelectedItem();
            ps.setString(1, value);
            ps.setString(2, jTextField_refer.getText());
            ps.setString(3, jTextField_dosemg.getText());
            ps.setString(4, jTextField_number.getText());
            ps.setString(5, jTextField_LOT.getText());
            ps.setString(6, jTextField_Issued.getText());
            ps.setString(7, jTextField_Exp.getText());
            ps.setString(8, jTextField_Dose.getText());
            ps.setString(9, jTextField_Effects.getText());
            ps.setString(10, jTextField_further.getText());
            ps.setString(11, jTextField_advice.getText());
            ps.setString(12, jTextField_machine.getText());
            ps.setString(13, jTextField_medication.getText());
            ps.setString(14, jTextField_pid.getText());
            ps.setString(15, jTextField_nhs.getText());
            ps.setString(16, jTextField_name.getText());
            ps.setString(17, jTextField_birth.getText());
            ps.setString(18, jTextField_address.getText());
            ps.executeUpdate();
        this.jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id", "tablets", "refer", "dosemg", "number", "LOT","Issued","Exp","Dose","Effects","further","advice","machine","medication","pid","nhs","naame","birth","address","id"}));
        this.fillHospitalJtable(this.jTable1, "");
        
            JOptionPane.showMessageDialog(null, "successfully inserted");
                    
                    } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
        
        }
        
        
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetActionPerformed
jTextField_refer.setText("");
jTextField_dosemg.setText("");
jTextField_number.setText("");
jTextField_LOT.setText("");
jTextField_Issued.setText("");
jTextField_Exp.setText("");
jTextField_Dose.setText("");
jTextField_Effects.setText("");
jTextField_further.setText("");
jTextField_advice.setText("");
jTextField_machine.setText("");
jTextField_medication.setText("");
jTextField_pid.setText("");
jTextField_nhs.setText("");
jTextField_name.setText("");
jTextField_birth.setText("");
jTextField_address.setText("");


    }//GEN-LAST:event_jButton_ResetActionPerformed

    private void jButton_PrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_PrescriptionActionPerformed
text_area.setForeground(Color.black);
text_area.setFont(new Font("Courier New", ITALIC, 18));
        
        
        //"Courier New", "ITALIC, 12);
        text_area.setText(text_area.getText()+"        your Reference:-"+jTextField_dosemg.getText()+"\n\n");
        text_area.setText(text_area.getText()+"        dosemg:-"+jTextField_dosemg.getText()+"\n\n");
        text_area.setText(text_area.getText()+"        LOT:-"+jTextField_LOT.getText()+"\n\n");
        text_area.setText(text_area.getText()+"        Issued:-"+jTextField_Issued.getText()+"\n\n");
        text_area.setText(text_area.getText()+"        Exp:-"+jTextField_Exp.getText()+"\n\n");
        text_area.setText(text_area.getText()+"        Effects:-"+jTextField_Effects.getText()+"\n\n");
        text_area.setText(text_area.getText()+"        advice:-"+jTextField_advice.getText()+"\n\n");
        text_area.setText(text_area.getText()+"        medication:-"+jTextField_medication.getText()+"\n\n");
        text_area.setText(text_area.getText()+"        id:-"+jTextField_pid.getText()+"\n\n");
        text_area.setText(text_area.getText()+"        name:-"+jTextField_name.getText()+"\n\n");
        text_area.setText(text_area.getText()+"        address:-"+jTextField_address.getText()+"\n\n");
                  
        
    }//GEN-LAST:event_jButton_PrescriptionActionPerformed

    private void jButton_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_printActionPerformed
try{
//text_area.print();
}
catch(Exception e){

}
                    
     
        
    }//GEN-LAST:event_jButton_printActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jTextField_referActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_referActionPerformed
         
    }//GEN-LAST:event_jTextField_referActionPerformed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jTextField_referKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_referKeyPressed
        
    }//GEN-LAST:event_jTextField_referKeyPressed

    private void jTextField_referKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_referKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
        }
    }//GEN-LAST:event_jTextField_referKeyTyped

    private void jTextField_ExpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_ExpKeyTyped
     if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
     }
    }//GEN-LAST:event_jTextField_ExpKeyTyped

    private void jTextField_pidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_pidKeyTyped
         if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
         }
    }//GEN-LAST:event_jTextField_pidKeyTyped

    private void jTextField_nhsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nhsKeyTyped
         if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
         }
    }//GEN-LAST:event_jTextField_nhsKeyTyped

    private void jTextField_birthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_birthKeyTyped
         if(!Character.isDigit(evt.getKeyChar())){
           evt.consume();
         }
    }//GEN-LAST:event_jTextField_birthKeyTyped

    private void jTextField_furtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_furtherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_furtherActionPerformed

    private void jButton_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_patientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_patientActionPerformed

    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        Connection con=MyConnection.getConnection();
        PreparedStatement ps;
    try {
        ps=con.prepareStatement("UPDATE `patient` SET `Name_of_Tablets`=?,`Reference_No`=?,`Dose_mg`=?,`Number_of_Tablets`=?,`LOT`=?,`Issued_Date`=?,`Exp_Date`=?,`Daily_Dose`=?,`Possible_Side_Effects`=?,`Further_information`=?,`Storage_Advice`=?,`Driving_and_Using_Machines`=?,`How_to_use_medication`=?,`Patient_ID`=?,`NHS_number`=?,`Patient_Name`=?,`Date_of_Birth`=?,`Patient_Address`=? WHERE `id`=?");
        String value=(String) jComboBox_tablets.getSelectedItem();
            ps.setString(1, value);
            ps.setString(2, jTextField_refer.getText());
            ps.setString(3, jTextField_dosemg.getText());
            ps.setString(4, jTextField_number.getText());
            ps.setString(5, jTextField_LOT.getText());
            ps.setString(6, jTextField_Issued.getText());
            ps.setString(7, jTextField_Exp.getText());
            ps.setString(8, jTextField_Dose.getText());
            ps.setString(9, jTextField_Effects.getText());
            ps.setString(10, jTextField_further.getText());
            ps.setString(11, jTextField_advice.getText());
            ps.setString(12, jTextField_machine.getText());
            ps.setString(13, jTextField_medication.getText());
            ps.setString(14, jTextField_pid.getText());
            ps.setString(15, jTextField_nhs.getText());
            ps.setString(16, jTextField_name.getText());
            ps.setString(17, jTextField_birth.getText());
            ps.setString(18, jTextField_address.getText());
            ps.setInt(19, Integer.valueOf(jTextField_Id.getText()));
          
            ps.executeUpdate();
        
        
        this.jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id", "tablets", "refer", "dosemg", "number", "LOT","Issued","Exp","Dose","Effects","further","advice","machine","medication","pid","nhs","naame","birth","address","id"}));
        this.fillHospitalJtable(this.jTable1, "");
         JOptionPane.showMessageDialog(null, "data updated");
    } catch(Exception ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
        
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        Connection con=MyConnection.getConnection();
        PreparedStatement ps;
        
    try {
        ps=con.prepareStatement("DELETE FROM `patient` WHERE `id`=?");
             ps.setInt(1, Integer.valueOf(jTextField_Id.getText()));
            ps.executeUpdate();
            
             this.jTable1.setModel(new DefaultTableModel(null,new Object[]{"Id", "tablets", "refer", "dosemg", "number", "LOT","Issued","Exp","Dose","Effects","further","advice","machine","medication","pid","nhs","naame","birth","address","id"}));
           this.fillHospitalJtable(this.jTable1, "");
             
    JOptionPane.showMessageDialog(null, "Deleted succesfully");
    } catch(Exception ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
       
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        jTextField_Id.setText(model.getValueAt(i, 0).toString());
        jComboBox_tablets.setSelectedItem(model.getValueAt(i, 1).toString());
             jTextField_refer.setText(model.getValueAt(i, 2).toString());
   jTextField_dosemg.setText(model.getValueAt(i, 3).toString());
   jTextField_number.setText(model.getValueAt(i, 4).toString());
   jTextField_LOT.setText(model.getValueAt(i, 5).toString());
   jTextField_Issued.setText(model.getValueAt(i, 6).toString());
   jTextField_Exp.setText(model.getValueAt(i, 7).toString());
   jTextField_Dose.setText(model.getValueAt(i, 8).toString());
   jTextField_Effects.setText(model.getValueAt(i, 9).toString());
   jTextField_further.setText(model.getValueAt(i, 10).toString());
   jTextField_advice.setText(model.getValueAt(i, 11).toString());
   jTextField_machine.setText(model.getValueAt(i, 12).toString());
   jTextField_medication.setText(model.getValueAt(i, 13).toString());
   jTextField_pid.setText(model.getValueAt(i, 14).toString());
   jTextField_nhs.setText(model.getValueAt(i, 15).toString());
   jTextField_name.setText(model.getValueAt(i, 16).toString());
   jTextField_birth.setText(model.getValueAt(i, 17).toString());
   jTextField_address.setText(model.getValueAt(i, 18).toString());
   
   
   
   
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField_dosemgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_dosemgActionPerformed
        
    }//GEN-LAST:event_jTextField_dosemgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }
public void fillHospitalJtable(JTable table, String valueToSearch){

Connection con=MyConnection.getConnection();
PreparedStatement ps;
    try {
        ps=con.prepareStatement("SELECT * FROM `patient` WHERE CONCAT(`Name_of_Tablets`, `Reference_No`, `Dose_mg`, `Number_of_Tablets`, `LOT`, `Issued_Date`, `Exp_Date`, `Daily_Dose`, `Possible_Side_Effects`, `Further_information`, `Storage_Advice`, `Driving_and_Using_Machines`, `How_to_Use_Medication`, `Patient_ID`, `NHS_number`, `Patient_Name`, `Date_of_Birth`, `Patient_Address`) LIKE ?");
    
    ps.setString(1, "%"+valueToSearch+"%");
    ResultSet rs=ps.executeQuery();
    DefaultTableModel model=(DefaultTableModel)table.getModel();
    Object[] row;
    while(rs.next()){
    row=new Object[19];
    row[0]=rs.getInt(1);
    row[1]=rs.getString(2);
    row[2]=rs.getString(3);
    row[3]=rs.getString(4);
    row[4]=rs.getString(5);
    row[5]=rs.getString(6);
    row[6]=rs.getString(7);
     row[7]=rs.getString(8);
      row[8]=rs.getString(9);
       row[9]=rs.getString(10);
        row[10]=rs.getString(11);
         row[11]=rs.getString(12);
          row[12]=rs.getString(13);
           row[13]=rs.getString(14);
            row[14]=rs.getString(15);
             row[15]=rs.getString(16);
              row[16]=rs.getString(17);
            row[17]=rs.getString(18);
             row[18]=rs.getString(19);
   model.addRow(row);
    }
    
    
    } catch (Exception ex) {
JOptionPane.showMessageDialog(null, ex);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Prescription;
    private javax.swing.JButton jButton_Reset;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_patient;
    private javax.swing.JButton jButton_print;
    private javax.swing.JComboBox<String> jComboBox_tablets;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Dose;
    private javax.swing.JTextField jTextField_Effects;
    private javax.swing.JTextField jTextField_Exp;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_Issued;
    private javax.swing.JTextField jTextField_LOT;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_advice;
    private javax.swing.JTextField jTextField_birth;
    private javax.swing.JTextField jTextField_dosemg;
    private javax.swing.JTextField jTextField_further;
    private javax.swing.JTextField jTextField_machine;
    private javax.swing.JTextField jTextField_medication;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_nhs;
    private javax.swing.JTextField jTextField_number;
    public javax.swing.JTextField jTextField_pid;
    private javax.swing.JTextField jTextField_refer;
    private java.awt.TextArea text_area;
    // End of variables declaration//GEN-END:variables


    
}
